"""add ai_request_log table

Revision ID: 18de3b34e4dd
Revises: fe56fa70289e
Create Date: 2026-09-27 16:44:47.863444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '18de3b34e4dd'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('data_class', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_vnd', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_log_created_at'), 'ai_request_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_request_log_created_at'), table_name='ai_request_log')
    op.drop_table('ai_request_log')
    # ### end Alembic commands ###
