"""add analytics_event table

Revision ID: 5ea267b0a7d6
Revises: f80757111191
Create Date: 2026-09-27 18:28:16.159977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5ea267b0a7d6'
down_revision = 'f80757111191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('visitor_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('src', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('check_id', sa.Uuid(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_event_created_at'), 'analytics_event', ['created_at'], unique=False)
    op.create_index('ix_analytics_event_event_created_at', 'analytics_event', ['event', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_event_event_created_at', table_name='analytics_event')
    op.drop_index(op.f('ix_analytics_event_created_at'), table_name='analytics_event')
    op.drop_table('analytics_event')
    # ### end Alembic commands ###
