"""add corpus tables

Revision ID: f80757111191
Revises: 18de3b34e4dd
Create Date: 2026-09-27 17:52:55.178612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f80757111191'
down_revision = '18de3b34e4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rubric_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('calibration_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dataset_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('split', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_run_created_at'), 'eval_run', ['created_at'], unique=False)
    op.create_table('training_corpus_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('prompt_redacted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('essay_redacted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_result', sa.JSON(), nullable=True),
    sa.Column('rubric_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('split', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('dataset_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('thumbs_down', sa.Boolean(), nullable=False),
    sa.Column('delete_code_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('check_id', sa.Uuid(), nullable=True),
    sa.Column('is_injection', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delete_code_hash')
    )
    op.create_index(op.f('ix_training_corpus_item_check_id'), 'training_corpus_item', ['check_id'], unique=False)
    op.create_index(op.f('ix_training_corpus_item_created_at'), 'training_corpus_item', ['created_at'], unique=False)
    op.create_table('human_label',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('labeler', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('criteria_scores', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('issue_verdicts', sa.JSON(), nullable=True),
    sa.Column('missed_issues', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['training_corpus_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_label_created_at'), 'human_label', ['created_at'], unique=False)
    op.create_index(op.f('ix_human_label_item_id'), 'human_label', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_label_item_id'), table_name='human_label')
    op.drop_index(op.f('ix_human_label_created_at'), table_name='human_label')
    op.drop_table('human_label')
    op.drop_index(op.f('ix_training_corpus_item_created_at'), table_name='training_corpus_item')
    op.drop_index(op.f('ix_training_corpus_item_check_id'), table_name='training_corpus_item')
    op.drop_table('training_corpus_item')
    op.drop_index(op.f('ix_eval_run_created_at'), table_name='eval_run')
    op.drop_table('eval_run')
    # ### end Alembic commands ###
